[package]
name = "gaia"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

[features]
Client = [ ]
Server = [ ]
LinuxClient = [ "ws" ]
ProtoWasmClient = [ ] #[ "wasm-bindgen", "web-sys" ]
FinalWasmClient = [ ] #[ ? ]
ProtoLinuxServer = [ "ws" ]
FinalLinuxServer = [ ] #[ ? ]

[dependencies]
ws = { version = "0.7.6", optional = true }
wasm-bindgen = { version = "0.2.50", optional = true }
web-sys = { version = "0.3.22", optional = true, features = [ "ErrorEvent", "MessageEvent", "WebSocket" ] }
