[package]
name = "gaia"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

[features]
Client = [ "gaia-data-transport/Client" ]
Server = [ "gaia-data-transport/Server" ]
ClientLinux = [ "gaia-data-transport/ClientLinux" ]
ProtoClientWasm = [ "gaia-data-transport/ProtoClientWasm" ]
FinalClientWasm = [ "gaia-data-transport/FinalClientWasm" ]
ProtoServerLinux = [ "gaia-data-transport/ProtoServerLinux" ]
FinalServerLinux = [ "gaia-data-transport/FinalServerLinux" ]

[dependencies]
gaia-data-transport = { path = "../gaia-data-transport" } # { git = "https://bitbucket.org/connorcarpenter/gaia-data-transport.git" }