[package]
name = "gaia"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

[features]
Client = [ ]
Server = [ ]
UdpClient = [ "laminar" ]
WebrtcClient = [ ]
UdpServer = [ "laminar" ]
WebrtcServer = [ ]

[dependencies]
laminar = { version = "*", optional = true }