[package]
name = "gaia"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

[features]
Client = [ ]
Server = [ ]
UdpClient = [ "laminar", "crossbeam-channel" ]
WebrtcClient = [ ]
UdpServer = [ "laminar", "crossbeam-channel" ]
WebrtcServer = [ ]

[dependencies]
laminar = { version = "0.3.2", git = "https://github.com/amethyst/laminar", optional = true }
crossbeam-channel = { version = "0.3", optional = true }
log = "0.4"