[package]
name = "gaia"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

[features]
Client = [ "gaia-data-transport/Client" ]
Server = [ "gaia-data-transport/Server" ]
LinuxClient = [ "gaia-data-transport/LinuxClient" ]
ProtoWasmClient = [ "gaia-data-transport/ProtoWasmClient" ]
FinalWasmClient = [ "gaia-data-transport/FinalWasmClient" ]
ProtoLinuxServer = [ "gaia-data-transport/ProtoLinuxServer" ]
FinalLinuxServer = [ "gaia-data-transport/FinalLinuxServer" ]

[dependencies]
gaia-data-transport = { path = "../gaia-data-transport" } # { git = "https://bitbucket.org/connorcarpenter/gaia-data-transport.git" }