[package]
name = "gaia"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gaia-data-transport = { path = "../gaia-data-transport" } # { git = "https://bitbucket.org/connorcarpenter/gaia-data-transport.git" }