[package]
name = "gaia"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

[features]
Client = [ "gaia-data-transport/Client" ]
Server = [ "gaia-data-transport/Server" ]
Linux = [ "gaia-data-transport/Linux" ]
Wasm = [ "gaia-data-transport/Wasm" ]

[dependencies]
gaia-data-transport = { path = "../gaia-data-transport" } # { git = "https://bitbucket.org/connorcarpenter/gaia-data-transport.git" }