[package]
name = "gaia-socket"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

[features]
UdpClient = [ "laminar", "crossbeam-channel" ]
WebrtcClient = [ ]
UdpServer = [ "laminar", "crossbeam-channel", "async-trait" ]
WebrtcServer = [ "webrtc-unreliable", "clap", "hyper", "tokio", "async-trait", "futures-channel",
    "futures-core", "futures-util", "env_logger" ]

[dependencies]
log = "0.4"
laminar = { version = "0.3.2", git = "https://github.com/amethyst/laminar", optional = true }
crossbeam-channel = { version = "0.3", optional = true }
webrtc-unreliable = { path = "../webrtc-unreliable", optional = true } # { git = "https://github.com/kyren/webrtc-unreliable", optional = true }
clap = { version = "2.32", optional = true}
hyper = { version = "0.13", features = ["stream"], optional = true }
tokio = { version = "0.2", features = ["macros"], optional = true }
async-trait = { version = "0.1.30", optional = true }
env_logger = { version = "0.7", optional = true }
futures-channel = { version = "0.3", features = ["sink"], optional = true }
futures-core = { version = "0.3", optional = true }
futures-sink = { version = "0.3", optional = true }
futures-util = { version = "0.3", features = ["sink"], optional = true }