[package]
name = "gaia-socket"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

[features]
UdpClient = [ "laminar", "crossbeam-channel" ]
WebrtcClient = [ ]
UdpServer = [ "laminar", "crossbeam-channel" ]
WebrtcServer = [ "webrtc-unreliable" ]

[dependencies]
log = "0.4"
laminar = { version = "0.3.2", git = "https://github.com/amethyst/laminar", optional = true }
crossbeam-channel = { version = "0.3", optional = true }
webrtc-unreliable = { git = "https://github.com/kyren/webrtc-unreliable", optional = true } # { path = "../webrtc-unreliable" }