[package]
name = "gaia"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

[features]
UdpClient = [ "gaia-socket/UdpClient" ]
WebrtcClient = [ "gaia-socket/WebrtcClient" ]
UdpServer = [ "gaia-socket/UdpServer" ]
WebrtcServer = [ "gaia-socket/WebrtcServer" ]

[dependencies]
gaia-socket = { path = "../gaia-socket" } # { git = "https://github.com/connorcarpenter/gaia-socket" } #
futures-channel = { version = "0.3", features = ["sink"] }
futures-core = { version = "0.3" }
futures-sink = { version = "0.3" }
futures-util = { version = "0.3", features = ["sink"] }